application: arunjit-test
version: 2013-03-07-endpoints
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css/.*
  static_dir: css

- url: /images/.*
  static_dir: images

- url: /js/.*
  static_dir: js

- url: .*
  script: main.app

